[project]
name = "cordic-visualizer"
version = "0.1.0"
description = "Streamlit CORDIC demo"
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"

dependencies = [
  "numpy",
  "matplotlib",
  "streamlit"
]
